//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal_Grupo08.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Clientes
    {
        [Display(Name = "#")]
        public int ID_Cliente { get; set; }
        [Display(Name = "Nombre del cliente")]
        public string Nombre { get; set; }
        [Display(Name = "Correo electronico")]
        public string Correo { get; set; }
        [Display(Name = "Numero telefonico")]
        public string Telefono { get; set; }
        [Display(Name = "DNI")]
        public string DNI { get; set; }
    }
}
