//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal_Grupo08.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Meseros
    {
        [Display(Name = "#")]
        public int ID_Mesero { get; set; }
        [Display(Name = "Nombre de mesero")]
        public string Nombre { get; set; }
        [Display(Name = "Nombre de usuario")]
        public string Usuario { get; set; }
        [Display(Name = "Estado de trabajador")]
        public Nullable<bool> Estado { get; set; }
    }
}
